export const datasources = [
  "Thông tin chung",
  "ACB",
  "Ampe kìm",
  "Bu lông cường độ cao",
  "Bu lông lục giác",
  "Bàn chải",
  "Bàn chải sắt",
  "Bàn nâng _ Bộ định vị Pallet",
  "Bàn ren",
  "Bàn đo lường kiểm tra",
  "Bào Tay",
  "Bánh xe",
  "Bát cước",
  "Bìa Acco",
  "Bìa mica",
  "Bìa màu",
  "Bình châm nhớt",
  "Bình chữa cháy",
  "Bình phun",
  "Bình xịt và vòi xịt",
  "Bóng",
  "Bóng búp a",
  "Bóng búp trang trí",
  "Bóng cao áp",
  "Bóng haloline star",
  "Bóng huỳnh quang",
  "Bóng led stick",
  "Bóng led trụ",
  "Bóng led tuýp",
  "Búa",
  "Búa cao su",
  "Búa cơ khí_ búa gò",
  "Búa gõ xỉ hàn",
  "Búa nhổ đinh",
  "Búa nhựa",
  "Búa rìu",
  "Búa tạ",
  "Búa đầu bi",
  "Búng mực tự động",
  "Bút",
  "Bút Ký",
  "Bút bi",
  "Bút chì_ chì kim",
  "Bút chì_ chì kim_ ruột chì_ tẩy_ gọt chì",
  "Bút gel nước",
  "Bút lông bảng",
  "Bút lông dầu",
  "Bút lông dầu_ bút ghi đĩa_ bút sơn",
  "Bút nhớ dòng",
  "Bút sơn",
  "Bút thử điện",
  "Bút xóa_ băng xóa_ ruột băng xóa",
  "Băng dính",
  "Băng dính 2 mặt",
  "Băng dính OPP",
  "Băng dính SIMILLY",
  "Băng dính giấy",
  "Băng dính_ hồ dán_ keo dán",
  "Băng xóa",
  "Bảng từ treo tường",
  "Bảo Hộ Lao Động",
  "Bật mực",
  "Bộ chìa vặn",
  "Bộ chìa vặn lục giác",
  "Bộ cấp và phụ kiện dây MIG",
  "Bộ cờ lê",
  "Bộ cờ lê tự động",
  "Bộ cờ lê vòng miệng",
  "Bộ dụng cụ chuyên dụng",
  "Bộ dụng cụ cầm tay",
  "Bộ dụng cụ dùng pin",
  "Bộ khẩu",
  "Bộ kìm",
  "Bộ lã ống đồng",
  "Bộ lăn sơn",
  "Bộ lục giác xếp",
  "Bộ máy cân mực",
  "Bộ mũi vít",
  "Bộ tuốc nơ vít đóng",
  "Bộ văn chìa lục giác",
  "Bộ đèn",
  "Bộ đầu khẩu",
  "Bộ đầu khẩu mũi vít",
  "Bộ đột lỗ tole thủy lực",
  "Bộ đục và mài lỗ",
  "Bộ ống nước làm vườn",
  "Bột giặt",
  "CHƯA PHÂN LOẠI",
  "Chia file giấy_ nhựa",
  "Chiếu sáng chuyên dụng",
  "Chiếu sáng dân dụng",
  "Chun vòng",
  "Chìa vặn lục giác",
  "Chất trợ hàn_ dung môi hàn",
  "Chổi cước",
  "Compa",
  "Con dấu",
  "Con dấu_ khay dấu_ mực dấu",
  "Các phụ kiện khác",
  "Cáp",
  "Cáp chuyên dụng",
  "Cáp nối cho dụng cụ đo",
  "Công cụ đánh dấu",
  "Công tắc trọn bộ",
  "Căn lá",
  "Cưa cầm tay",
  "Cưa cầm tay và lưỡi cưa",
  "Cần cưa và giật cành",
  "Cần hít ốc",
  "Cần nối",
  "Cần siết",
  "Cần siết lực",
  "Cần siết lực điện tử dùng pin",
  "Cần siết đầu lắc léo",
  "Cần trượt",
  "Cầu dao",
  "Cắt băng dính",
  "Cặp đựng tài liệu",
  "Cờ lê 2 đầu miệng",
  "Cờ lê 2 đầu vòng",
  "Cờ lê chuyên dụng",
  "Cờ lê hãm",
  "Cờ lê lực",
  "Cờ lê móc",
  "Cờ lê tự động",
  "Cờ lê vòng miệng",
  "Cờ lê đuôi chuột",
  "Cờ lê đóng",
  "DMSP test tích hợp 1",
  "Danh mục sản phẩm nam 3_",
  "Dao",
  "Dao cắt ống",
  "Dao cố định lưỡi",
  "Dao gấp",
  "Dao phay ren",
  "Dao rọc cáp và lưỡi",
  "Dao rọc giấy",
  "Dao rọc giấy và lưỡi dao",
  "Dao tiện đứt và cắt rãnh",
  "Dao và lưỡi dao",
  "Dao đa năng và lưỡi",
  "Driver _ bộ nguồn _",
  "Dây an toàn",
  "Dây cáp cuộn nhỏ",
  "Dây cáp viễn thông",
  "Dây cáp điều khiển",
  "Dây hàn",
  "Dây hàn lõi chảy",
  "Dây thừng",
  "Dây đai",
  "Dây điện",
  "Dũa",
  "Dưỡng đo",
  "Dầu cắt _ phụ gia",
  "Dập ghim",
  "Dập ghim và đinh ghim",
  "Dụng cụ chằng_ hạ hàng",
  "Dụng cụ cưa và lưỡi cưa",
  "Dụng cụ cầm tay",
  "Dụng cụ cầm tay khác",
  "Dụng cụ cắt kính",
  "Dụng cụ cắt và lưỡi cắt",
  "Dụng cụ dò",
  "Dụng cụ dùng pin công trường và phụ kiện",
  "Dụng cụ kẹp",
  "Dụng cụ làm sạch sàn",
  "Dụng cụ lấy dấu",
  "Dụng cụ mài và cắt",
  "Dụng cụ nhặt ốc bằng từ tính",
  "Dụng cụ uốn ống",
  "Dụng cụ và thiết bị hàn thiếc",
  "Dụng cụ và thiết bị phá dỡ",
  "Dụng cụ văn phòng",
  "Dụng cụ vặn tuýp",
  "Dụng cụ xét tâm phôi",
  "Dụng cụ điện của thợ điện",
  "Dụng cụ điện dùng cho vách thạch cao và tường",
  "Dụng cụ đo",
  "Dụng cụ đo khác",
  "Dụng cụ đo lỗ",
  "Dụng cụ đo môi trường",
  "Dụng cụ đo sâu",
  "Dụng cụ đo và phụ kiện",
  "Dụng cụ đột lỗ",
  "Dụng cụ đục lỗ",
  "Eke vuông",
  "File 3 dây",
  "File càng cua",
  "File còng",
  "File còng D",
  "File còng nhẫn",
  "File hộp",
  "File hở",
  "File khóa hộp",
  "File lá",
  "File rút gáy",
  "File tầng_ khay tầng",
  "File vát góc",
  "File_ bìa",
  "Ghim bấm và đinh ghim",
  "Ghim cài_ ghim cắm bảng",
  "Giàn giáo",
  "Giày bảo hộ",
  "Giũa",
  "Giũa dẹp",
  "Giũa tam giác",
  "Giũa tròn",
  "Giũa và bộ giũa",
  "Giũa và đục",
  "Giấy decan_ giấy nhãn tomy",
  "Giấy giới thiệu",
  "Giấy in A1_ A0",
  "Giấy in A3",
  "Giấy in A4",
  "Giấy in A5",
  "Giấy in màu",
  "Giấy in_ Photo",
  "Giấy nhám",
  "Giấy nhắn việc",
  "Giấy phân trang",
  "Giấy than",
  "Giấy văn phòng",
  "Giấy vệ sinh",
  "Giấy ép plastic",
  "Giẻ lau_ khăn tắm và khăn lau khô",
  "Găng bảo hộ",
  "Gương kiểm tra",
  "Gọt chì",
  "Hàn cắt Plasma",
  "Hóa chất khác",
  "Hóa chất tẩy rửa",
  "Hóa chất tẩy rửa Canxi_ vết ố và rỉ sét",
  "Hóa chất tẩy rửa dầu mỡ",
  "Hóa chất tẩy rửa và xử lý bề mặt",
  "Hóa chất tẩy rửa và đánh bóng kim loại",
  "Hóa chất xử lý nước thải",
  "Hóa đơn bán lẻ",
  "Hạt công tắc",
  "Hạt mài_Cát",
  "Hồ dán - keo dán",
  "Hồ khô",
  "Hồ nước",
  "Keo dán",
  "Keo dán_ chất kết dính và bôi trơn",
  "Khay cắm bút",
  "Khác",
  "Không xác định",
  "Khăn giấy",
  "Khởi động từ",
  "Kéo",
  "Kéo cắt cành",
  "Kéo cắt cáp",
  "Kéo cắt tôn",
  "Kéo cắt ống",
  "Kéo và dụng cụ cắt",
  "Kéo văn phòng",
  "Kìm bấm cos",
  "Kìm bấm lỗ",
  "Kìm chuyên dụng",
  "Kìm chết",
  "Kìm càng cua",
  "Kìm cắt",
  "Kìm cắt cáp",
  "Kìm cắt sắt",
  "Kìm cặp",
  "Kìm kẹp 2 lỗ",
  "Kìm mỏ quạ",
  "Kìm mở phe",
  "Kìm nhọn",
  "Kìm tuốt dây",
  "Kìm đa năng",
  "Kìm điện _Kìm răng_",
  "Kích",
  "Kích nâng",
  "Kính bảo hộ",
  "Kẹp hàn",
  "Kẹp đen_ kẹp mầu",
  "Led batten",
  "Led chiếu điểm _spotlight_",
  "Led chống thấm",
  "Led downlight",
  "Led dây",
  "Led dây 220v",
  "Led highbay",
  "Led panel",
  "Led pha",
  "Led spotlight",
  "Lưu trữ dụng cụ",
  "Lưỡi cưa",
  "Lưỡi cưa máy",
  "Lưỡi cắt máy",
  "Lưỡi dao",
  "Lưỡi dao rọc giấy",
  "MCB",
  "MCCB",
  "Máng nhựa",
  "Máng đèn",
  "Máy buộc đai thép",
  "Máy bào",
  "Máy bơm hơi dùng pin",
  "Máy bơm nước",
  "Máy chà nhám",
  "Máy chà nhám vòng",
  "Máy chà sàn",
  "Máy cân mực",
  "Máy cưa bàn",
  "Máy cưa kiếm",
  "Máy cưa lọng",
  "Máy cưa vòng",
  "Máy cưa xích",
  "Máy cưa đa góc",
  "Máy cưa đĩa",
  "Máy cầm tay",
  "Máy cắt Oxy",
  "Máy cắt bê tông",
  "Máy cắt cành",
  "Máy cắt cỏ",
  "Máy cắt gạch_đá",
  "Máy cắt nhôm",
  "Máy cắt rung",
  "Máy cắt sắt",
  "Máy dò",
  "Máy dò đa năng",
  "Máy ghép mộng",
  "Máy hàn",
  "Máy hàn MIG",
  "Máy hàn MIG và phụ kiện",
  "Máy hàn TIG",
  "Máy hàn nhựa",
  "Máy hàn que",
  "Máy hàn đa năng",
  "Máy hút bụi cầm tay",
  "Máy hút bụi và phụ kiện",
  "Máy khoan",
  "Máy khoan bàn",
  "Máy khoan bê tông",
  "Máy khoan góc pin",
  "Máy khoan góc điện",
  "Máy khoan pin",
  "Máy khoan rút lõi",
  "Máy khoan từ",
  "Máy khoan điện",
  "Máy kiểm tra thiết bị cầm tay",
  "Máy làm sạch bề mặt",
  "Máy làm sạch đa năng",
  "Máy làm vườn",
  "Máy mài bàn",
  "Máy mài góc",
  "Máy mài khí nén",
  "Máy mài thẳng",
  "Máy phay",
  "Máy phay cạnh",
  "Máy phay dùng pin",
  "Máy phun rửa",
  "Máy phun rửa áp lực",
  "Máy phun thuốc",
  "Máy phun xịt",
  "Máy phun xịt rửa",
  "Máy phát điện",
  "Máy quét_ máy thổi bụi và máy thổi lá",
  "Máy siết bu lông",
  "Máy siết cắt bu lông",
  "Máy thổi bụi",
  "Máy thổi khí",
  "Máy thổi lá",
  "Máy thủy bình",
  "Máy tán đinh",
  "Máy tính cầm tay",
  "Máy tỉa hàng rào",
  "Máy vát mép",
  "Máy văn phòng",
  "Máy vặn bu lông",
  "Máy vặn bu lông góc",
  "Máy vặn vít",
  "Máy vặn vít pin",
  "Máy vặn vít điện",
  "Máy điện",
  "Máy đo khoảng cách laser",
  "Máy đo tốc độ vòng quay",
  "Máy đánh bóng",
  "Máy đột lỗ",
  "Máy đục bê tông",
  "Mũ bảo hộ",
  "Mũi doa",
  "Mũi doa máy",
  "Mũi doa tay",
  "Mũi khoan",
  "Mũi khoét",
  "Mũi mài",
  "Mũi phay",
  "Mũi phay ngón",
  "Mũi taro",
  "Mũi taro và bàn ren",
  "Mũi vít",
  "Mũi vít đóng",
  "Mặt công tắc",
  "Mỏ hàn",
  "Mỏ hàn TIG",
  "Mỏ lết dây_ mỏ lết xích",
  "Mỏ lết răng _Kìm nước_",
  "Mỏ lết thường",
  "Nhám cuộn",
  "Nhám tờ",
  "Nhám vòng",
  "Nhám đĩa",
  "Nhíp gắp linh kiện",
  "Nhóm khác",
  "Nhổ ghim",
  "Nâng hạ_ kho_ phụ trợ",
  "Nút nhấn",
  "Nước giặt",
  "Nước giặt_ bột giặt",
  "Nước lau nhà",
  "Nước lau sàn",
  "Nước rửa chén",
  "Nước rửa tay",
  "Nước suối",
  "Nước tẩy nhà vệ sinh",
  "Palăng",
  "Palăng kéo tay",
  "Palăng điện",
  "Panme",
  "Phiếu thu_ phiếu chi",
  "Phong bì",
  "Phấn",
  "Phụ kiện",
  "Phụ kiện cho máy phun xịt",
  "Phụ kiện chuyên dụng",
  "Phụ kiện chà nhám",
  "Phụ kiện cần siết lực",
  "Phụ kiện cắt gọt",
  "Phụ kiện hàn",
  "Phụ kiện khác",
  "Phụ kiện kim khí",
  "Phụ kiện máy bơm nước",
  "Phụ kiện máy khoan",
  "Phụ kiện máy làm vườn",
  "Phụ kiện máy mài",
  "Phụ kiện máy phay",
  "Phụ kiện phun cát_hạt mài",
  "Phụ kiện súng khò nhiệt",
  "Phụ kiện thay thế dụng cụ cầm tay",
  "Phụ kiện thiết bị nâng hạ",
  "Phụ kiện thiết bị điện",
  "Phụ kiện thiết bị đo kiểm tra điện",
  "Phụ kiện tuýp",
  "Phụ kiện đồng hồ so",
  "Phụ kiện đục phá",
  "Phụ tùng",
  "Phụ tùng thay thế dụng cụ điện",
  "Pin",
  "Pin 12V",
  "Pin 9V",
  "Pin cúc CR_ LR",
  "Pin máy",
  "Pin tiểu AA",
  "Pin và phụ kiện máy pin",
  "Pin đũa AAA",
  "Pin đại D",
  "Que hàn",
  "Que hàn TIG",
  "Quạt",
  "Quạt dùng pin",
  "Quần áo bảo hộ",
  "RCCB_ RCBO_ ELCB",
  "Ruột bút",
  "Ruột băng xóa",
  "Ruột chì",
  "Ruột ghim",
  "Rô to",
  "Rơ le",
  "Súng bơm mỡ",
  "Súng bấm ghim",
  "Súng bắn keo",
  "Súng bắn silicon",
  "Súng bắn đinh",
  "Súng hàn MIG",
  "Súng khò nhiệt dùng pin",
  "Súng khò nhiệt dùng điện",
  "Sơn",
  "Sơn và thiết bị sơn",
  "Sạc pin",
  "Sổ bìa cứng",
  "Sổ bìa mềm",
  "Sổ công văn đi",
  "Sổ công văn đến",
  "Sổ giả da",
  "Sổ kế toán",
  "Tay quay taro",
  "Tay vặn chữ thập",
  "Tay vặn khẩu",
  "Thang",
  "Thang chữ A",
  "Thang ghế",
  "Thang gấp",
  "Thang gấp và thang rút",
  "Thang rút",
  "Thang thẳng",
  "Thang đa năng",
  "Thanh ren toàn phần",
  "Thiết bị Megomet",
  "Thiết bị bảo hộ hàn",
  "Thiết bị chiếu sáng",
  "Thiết bị chụp ảnh nhiệt",
  "Thiết bị hiệu chuẩn đa năng",
  "Thiết bị ngoài trời",
  "Thiết bị ngành nước",
  "Thiết bị phân tích chất lượng điện",
  "Thiết bị phân tích công suất",
  "Thiết bị sơn",
  "Thiết bị đo dòng dò",
  "Thiết bị đo dòng dư",
  "Thiết bị đo khoảng cách",
  "Thiết bị đo khí",
  "Thiết bị đo nhiệt độ",
  "Thiết bị đo nhiệt độ độ ẩm",
  "Thiết bị đo thứ tự pha",
  "Thiết bị đo tiếng ồn",
  "Thiết bị đo tốc độ gió",
  "Thiết bị đo ánh sáng",
  "Thiết bị đo đa năng",
  "Thiết bị đo điện trở",
  "Thiết bị đo điện áp",
  "Thùng rác",
  "Thùng rác _ Hộp đựng rác",
  "Thùng đồ nghề",
  "Thùng đựng rác công nghiệp",
  "Thước",
  "Thước cuộn",
  "Thước cặp",
  "Thước dây",
  "Thước kẻ",
  "Thước thẳng_ thước lá",
  "Thước thủy",
  "Thước thủy và phụ kiện",
  "Thước ê ke",
  "Thước đo cơ khí",
  "Thước đo góc",
  "Thước đo khe hở",
  "Thước đo mối hàn",
  "Thước đo độ cao",
  "Thước đo độ dày",
  "Trình ký",
  "Tuýp vặn khẩu _Tuýp ống điếu_",
  "Tuốc nơ vít 2 đầu",
  "Tuốc nơ vít và bộ tuốc nơ vít",
  "Tuốc nơ vít và chìa vặn",
  "Tuốc nơ vít đóng và bộ",
  "Tuốc nơ vít đầu khẩu",
  "Túi khuy",
  "Túi nilon_ túi zip",
  "Túi đựng dụng cụ_ Balo",
  "Túi đựng rác",
  "Tạp phẩm",
  "Tạp phẩm khác",
  "Tẩy",
  "Tẩy rửa_ vệ sinh nhà cửa",
  "Tời",
  "Tủ điện",
  "Tủ đồ nghề",
  "Vali đựng đồ nghề",
  "Vam",
  "Vam kẹp C",
  "Vam kẹp F",
  "Vít",
  "Vít tự khoan",
  "Vòng đệm _Long đen_",
  "Văn phòng phẩm khác",
  "Vật tư công nghiệp",
  "Vật tư hàn",
  "Vật tư mài_ đánh bóng",
  "Vật tư phụ",
  "Vật tư tiêu hao MIG",
  "Vệ sinh công nghiệp",
  "Xe nâng dầu",
  "Xe nâng tay",
  "Xe nâng điện",
  "Xe đẩy dụng cụ",
  "Xe đẩy hàng",
  "Xe đẩy hàng 4 bánh",
  "Xe đẩy đo đường",
  "Xà beng",
  "Xà phòng bánh",
  "Xô và thùng vệ sinh",
  "beau is afraid",
  "băng dính điện",
  "khay dấu",
  "mực dấu",
  "sensor",
  "test1",
  "test2",
  "test3",
  "Áo khoác dùng pin",
  "Ê tô",
  "Đai ốc cường độ cao",
  "Đai ốc lục giác",
  "Đe cơ khí",
  "Đinh thép",
  "Đinh tán",
  "Đinh tán đầu chìm",
  "Điện",
  "Điện nhẹ",
  "Đo kiểm tra điện",
  "Đàm và loa công trường dùng pin",
  "Đá cắt",
  "Đá mài",
  "Đá mài đá cắt",
  "Đèn",
  "Đèn công trường dùng pin",
  "Đèn đường",
  "Đĩa cước",
  "Đĩa cắt",
  "Đĩa nhám xếp",
  "Đầu búa",
  "Đầu bắn tôn",
  "Đầu chuyển khẩu",
  "Đầu giữ từ",
  "Đầu khẩu",
  "Đầu khẩu mũi vít",
  "Đầu khẩu và bộ",
  "Đầu nối",
  "Đầu nối dài",
  "Đế từ_ khối V",
  "Đồng hồ khí",
  "Đồng hồ so",
  "Đồng hồ so và phụ kiện",
  "Đồng hồ vạn năng",
  "Đồng hồ đo sâu",
  "Đột",
  "Đục",
  "Đục gỗ",
  "Đục lỗ",
  "Đục lỗ và bộ đục lỗ",
  "Đục lỗ và cán",
  "Đục sắt",
  "Ống luồn dây",
  "Ống và máng nhựa",
  "Ống và phụ kiện TIG",
  "Ổ cắm",
  "Ổ cắm TV_ Điện thoại_ Mạng",
  "Ổ cắm công nghiệp",
  "Ổ cắm công tắc hỗn hợp",
  "Ổ cắm kéo dài",
];
